### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by JamiKettunen** [sailfishos-oneplus5/important#1]
- [ ] Fix droidmedia make build error (https://pastebin.com/XdrNLLeq)
- [ ] Fix garbled video for first 2 seconds of recording & very visible "compression artifacts" when moving even slightly
- [ ] Improve camera and add more resolution settings to match O<sub>2</sub>OS defaults
- [ ] Fix call audio & microphone (audioflingerglue)
- [ ] Fix BT instability issues
- [ ] Do something with notification slider
- [ ] Enable LEDs on physical buttons when screen is on
- [ ] Map right physical button to back also
- [ ] Figure out a better workaround for broken tar issue on TWRP (uses all ram and gives "error 7"; ~10 GB swapfile works for now)
- [ ] Ensure microphone routing from headsets works
